### ISSUE TITLE
無法找到玩家

### ISSUE THREAD

**Issue by NGCCI** [LittleNightmare/UsedName#1]

**Comment by NGCCI** [comment]
国际服版本6.21 opcode:533
提示无法找到玩家，要更新好友列表，更新后还是无法找到玩家
不知道是opcode錯了還是不支持國際服6.21

**Comment by LittleNightmare** [comment]
> 不知道是opcode錯了還是不支持國際服6.21

如果opcode错误，可以从设置里参考介绍手动更新一下

但手动更新好友列表（使用命令，还有设置里的更新）是不需要opcode的，除非xivcommon有问题

可以把你搜索的方式详细说一下吗？有可能是我命令的搜索逻辑写错了，但如果你用的是右键的。。。~~那可能xivcommon出问题，大概可以从其他插件的xivcommon偷过来，覆盖一下~~ 不应该出问题

**Comment by LittleNightmare** [comment]
我刚刚提交了一个新的版本，可能解决这个问题https://github.com/goatcorp/DalamudPluginsD17/pull/556

**Comment by LittleNightmare** [comment]
额，没有后续反馈，我就当是解决了吧。有问题再说
